sudo: required
language: generic 
services:
    - docker

before_install:
    - docker build -t realdw6/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true realdw6/docker-react npm run test